# Goal
colav_interfaces/MissionRequest mission_request

---
# Result
bool success
string status_message

---
# Feedback - This will return the serialised protobuf for controllerfeedback
std_msgs/ByteMultiArray serialised_protobuf_controller_feedback
